---
title: "Homework6"
author: "Yuxin"
date: "2018.11.24"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(purrr)
```

# Problem 1

## Part1: Read and clean data
```{r}
homicide_url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homicide_data = read.csv(url(homicide_url)) %>%
  janitor::clean_names() %>%
  as_tibble()

### Create a new variable containes city and state
homicide_data = homicide_data %>%
  mutate(city_state = str_c(city, state, sep = ", " )) %>%
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")))


### Modifiy variable race and age
homicide_data = homicide_data %>%
  mutate(solved = as.numeric(disposition == "Closed by arrest"),
         victim_race = ifelse(victim_race == "White", "white", "non-white"),
         victim_race = fct_relevel(victim_race, ref = "white"),
         victim_age = as.numeric(victim_age))
```

## Part2: Fit a model for Baltimore
```{r}
homicide_baltimore = homicide_data %>%
  filter(city_state == "Baltimore, MD")
fit_logistic = homicide_baltimore %>%
  glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())


fit_logistic %>% 
  broom::tidy() %>% 
  select(term, estimate, std.error) %>%
  mutate(Term = recode(term, "victim_racenon-white" = "victim_race: non-white", "victim_sexMale" = "victim_sex: male"), 
         "Odds Ratio" = exp(estimate), 
         "Lower bound" = exp(estimate -1.96*std.error), 
         "Upper bound" = exp(estimate +1.96*std.error)) %>%
  select(Term, "Odds Ratio", "Lower bound", "Upper bound") %>%
  knitr::kable(digits = 3)
```

## Part3: Fit the model for all cities
```{r}

### Write a function to fit the model 
logistic_fit = function(df){
 glm(solved ~victim_age + victim_race + victim_sex, data =df, family = binomial()) %>%
 broom::tidy() %>%
 mutate(ors = exp(estimate),
        conf_low = exp(estimate -1.96*std.error),
        conf_high = exp(estimate +1.96*std.error)) %>%
    select(term, ors, conf_low, conf_high) %>%
    filter(term == "victim_racenon-white")
}
  
## Fit the model
homicide_city = homicide_data %>%
  select(city_state, solved, victim_sex, victim_race, victim_age) %>%
  group_by(city_state) %>%
  filter(victim_sex %in% c("Female", "Male", "Unknown")) %>% 
  nest() %>%
  mutate(log_models = map(data, logistic_fit)) %>%
  select(-data) %>%
  unnest()

```
